### ISSUE TITLE
ShiftPlanning is updating their API endpoints

### ISSUE THREAD

**Issue by ReezyG** [Kylerchrdsn/ShiftPlanning-ruby#3]
they're removing the URI endpoing `https://shiftplanning.com/api` and changing it to `https://humanity.com/api`. This removal is scheduled for March 4th 1:30 AM PST. 

I believe you only have to update the uri in the `config.rb` and swap `shiftplanning.com/api` for `humanity.com/api`

**Comment by Kylerchrdsn** [comment]
Sorry for the delay. I'm sure you've already forked this repo, but I'll get this fixed.

**Comment by Kylerchrdsn** [comment]
#4 Should have resolved this.
